# Generated by Django 5.1.4 on 2025-01-11 14:23

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0002_remove_userprofile_language_and_more"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="UserProfile",
            new_name="UserInput",
        ),
    ]
